### ISSUE TITLE
With the grey box gone, is this extension now permanently broken?

### ISSUE THREAD

**Issue by beti88** [hnmr293/sd-webui-llul#33] opened 2023-05-28 08:19 UTC
For more than a month now people have been asking about this issue and we have sadly no info. I tried this on A1111, Vlad, after multiple clean installs too, and no, the grey box is gone.

Should we move on? Without that functionality this extensions is sadly pointless

**Comment by ryankhart** [comment] 2023-05-29 23:48
Same here.

Duplicate of #31. (I don't mean to scold you. I just thought it would be useful to whoever maintains these issues in the future if this issue ever gets fixed.)

**Comment by beti88** [comment] 2023-05-30 05:22
downgrading all the way back to on Apr 1 8252c84 is the only way I found to bring the grey box back

**Comment by zyip** [comment] 2023-06-03 06:17
try a history insted:
git clone https://github.com/hnmr293/sd-webui-llul.git
cd sd-webui-llul
git reset --hard  631059c

**Comment by j2l** [comment] 2023-06-28 09:27
Thank you @zyip

**Comment by gpww** [comment] 2023-07-19 09:19
same problem, no grey box!

**Comment by wahahai** [comment] 2023-07-22 19:25
631959c There is a black box, the background image cannot be loaded

**Comment by Duemellon** [comment] 2023-08-01 00:24
I have never used this before & I was wondering why there were no tutorials explaining how to get the box for selection. I see this was broken during a CN update?

**Comment by Nuullll** [comment] 2023-08-13 13:07
Proposed a PR: https://github.com/hnmr293/sd-webui-llul/pull/34

**Comment by maxchiron** [comment] 2023-08-23 19:47
@Nuullll Thanks for the fix professor! 

I've installed your fork and still not got the grey box. May I ask **this extension is used in text2image or image2image tab?** I see both tabs have the llul block. 

Thanks~

**Comment by nodegraphics** [comment] 2023-10-15 09:50
no box or anything. no explanation or any screencap of how this mysterious grey box looks like or how its manipulated :) I think this extension is dead.....

**Closed as completed** 2023-11-13 15:36 UTC
